# Data configuration for Tennis Match Predictor

source:
  github_repo: "JeffSackmann/tennis_atp"
  selected_year: 1991
  tourney_levels:
    - "G"  # Grand Slam
    - "F"  # Tour Finals
    - "M"  # Masters
    - "A"  # ATP Tour

features:
  rolling_windows:
    - 3
    - 5
    - 10
  stats_columns_mean:
    - "p_ace"
    - "p_df"
    - "p_svpt"
    - "p_1stIn"
    - "p_1stWon"
    - "p_2ndWon"
    - "p_SvGms"
    - "p_bpSaved"
    - "p_bpFaced"
    - "opponent_rank_points"
    - "o_ace"
    - "o_df"
    - "o_svpt"
    - "o_1stIn"
    - "o_1stWon"
    - "o_2ndWon"
    - "o_SvGms"
    - "o_bpSaved"
    - "o_bpFaced"
    - "minutes"
  stats_columns_sum:
    - "minutes"
    - "results"
  elo_k_factor: 32.0
  elo_initial_rating: 1500.0

inference_data_path: "data/"
matches_results_file: "matches_results.pkl"
tournament_info_file: "tournament_info.pkl"
